In [1]:
import pandas as pd
data = pd.read_csv("CarPrice_assignment.csv").drop("car_ID",axis=1)
data.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [2]:
from pycaret.regression import *
st=setup(data=data,target="price",remove_multicollinearity=True,train_size=0.7
         ,polynomial_features=True,remove_outliers=True)

In [3]:
bst=compare_models(include=["lr",'lasso','ridge','huber'])

In [4]:
evaluate_model(bst)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [5]:
create_model(bst)

HuberRegressor()

In [6]:
tm=tune_model(bst)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [27]:
data=pd.read_csv("erroranalysed.csv").drop("index",axis=1)
data

     curbweight  cylindernumber   carvolume   enginepower  averagempg    price
0          2548               0  528019.904  4.613226e+06       23.70  13495.0
1          2548               0  528019.904  4.613226e+06       23.70  16500.0
2          2823               1  587592.640  4.455542e+06       22.15  16500.0
3          2337               0  634816.956  3.841257e+06       26.70  13950.0
4          2824               1  636734.832  4.917072e+06       19.80  17450.0
..          ...             ...         ...           ...         ...      ...
178        2952               0  721961.760  5.919961e+06       25.25  16845.0
179        3049               0  720913.920  6.226185e+06       21.70  19045.0
180        3012               1  721961.760  7.245706e+06       20.25  21485.0
181        3217               1  721961.760  4.242935e+06       26.45  22470.0
182        3062               0  721961.760  5.919961e+06       21.70  22625.0

[183 rows x 6 columns]

In [28]:
st1=setup(data=data,target="price",remove_multicollinearity=True,train_size=0.7
         ,remove_outliers=True)

In [29]:
bst1=compare_models(include=["lr",'lasso','ridge','huber'])

In [30]:
evaluate_model(bst1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [31]:
tm1=tune_model(bst1)

Fitting 10 folds for each of 2 candidates, totalling 20 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).